### ISSUE TITLE
Doc issue 

### ISSUE THREAD

**Issue by GovindMalviya** [ua-parser/uap-csharp#1]
Statement in usage section

<code>
Client c = uaParser.Parse(uaString);
</code>

should be 
<code>
ClientInfo c = uaParser.Parse(uaString);
</code>

because When installed package (UAParser) through nuget this code doesn't work and after this edit it worked. 

one more thing authors' githib links are not valid is missing : after http

**Comment by Ironholds** [comment]
Thanks; want to submit a patch?

**Comment by GovindMalviya** [comment]
Sent pull request

**Comment by enemaerke** [comment]
The issue has been resolved in pr #5
