### ISSUE TITLE
Update NuGet package with latest YAML files

### ISSUE THREAD

**Issue by mattlangis** [ua-parser/uap-csharp#10]
Hello!

I've been working with UAParser NuGet package, but it seems not up-to-date when we compare with the latest uap-core. Basically, it's missing Windows 10. (detected as "Windows")

Is it possible to push the latest version to NuGet?

I did rebuild locally and it seems fine when we simply pull the yaml file.

Thanks :)
Matt

**Comment by enemaerke** [comment]
You can pull the latest yaml file from uap-core and then use the static `Parser.FromYaml` to obtain a `Parser`instance that uses the newest regexs. The C# port is embedding one specific snapshot of the regex definitions but is bound to be outdated regularly, so the static overload let's you decide when to upgrade. Hope this helps.

**Comment by mattlangis** [comment]
Thanks!
