### ISSUE TITLE
2.0.0 major breaking changes

### ISSUE THREAD

**Issue by niemyjski** [ua-parser/uap-csharp#12]
There is no change log or updated read me with usages.. Even bigger you guys seem to have gotten rid of `info.Device.IsSpider` Where has this moved to?

**Comment by niemyjski** [comment]
Can you add this back as an extension method or property? 

https://github.com/ua-parser/uap-csharp/commit/9494702226f2843d3fef957eae89c2f99fd58d80

**Comment by enemaerke** [comment]
Apologies for missing change log/readme, I should have taken greater care in ensuring a clear migration. 

I did bump the major version to signal the change in the API. I'll take a look at detecting the spiders, the detection was largely removed as a first class citizen from the regex'es backing the API but it seems like something can be done to emulate an IsSpider property on the Device.

Hope that helps

**Comment by niemyjski** [comment]
That would help greatly! We use it for bot detection on https://github.com/exceptionless/Exceptionless

**Comment by enemaerke** [comment]
I'll get on it tomorrow (it closing in on midnight in my timezone)

**Comment by enemaerke** [comment]
@niemyjski I just uploaded version 2.1.0 to nuget.org which reverts back to the ClientInfo class and also exposes the IsSpider property again. Hope this helps and sorry for the broken api. I'll close the issue, feel free to reopen something is not as expected

**Comment by niemyjski** [comment]
Thank you!
