### ISSUE TITLE
Enable compiled regular expressions

### ISSUE THREAD

**Issue by GSPP** [ua-parser/uap-csharp#16]
In uap-csharp there is the following comment:

                // TODO: potentially allow parser to specify e.g. to use 
                // compiled regular expressions which are faster but increase 
                // startup time
                
                return new Regex(pattern);

I found significant performance gains when changing this to

                return new Regex(pattern, RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.Singleline);

I believe that `Compiled` is responsible for the gains. I don't see why UA parsign should be culture-dependent so I added `CultureInvariant`. Also, do any of the regular expressions depend on newline behavior (which means that `.` does or does not match '\n')? I don't think so. Using `Singleline` is faster because it speeds up the `.` pattern element.

I request that `RegexOptions.CultureInvariant | RegexOptions.Singleline` are always enabled and that `Compiled` is either enabled as an option or always enabled. I have not measured startup time deterioration. If this is not highly significant, compiled expressions should be the default.

Thanks for providing such a useful library!

**Comment by enemaerke** [comment]
Hi @GSPP . Thanks for the groundwork, I'll try to carve out some time to experiment on the options on the RegExes and see if there is a sweetspot or perhaps some options/config parameter could be warranted.

**Comment by enemaerke** [comment]
Hi Again @GSPP. I've played around with adding an option to the parser that allows for setting the regex'es to compiled. It does affect startup time (from ~30ms to ~150ms on my laptop) but I don't see any real increased performance when running it on the testset I already have.

You mentioned that you've seen performance increases, do you have some test data I can get my hands on by any chance?

**Comment by GSPP** [comment]
I'll get back to you. Might take a few days.

Where is your data from? Mine is from weblogs of a fairly big site that I run. Should be 300m requests. I think I offered by mail to someone to contribute data. Not sure what happened back then.

**Comment by enemaerke** [comment]
I've just run on the existing testdata that exercises/validates the full range of the regex, so that is by no means a real world scenario but it was what I had in hand when I experimented.

Looking forward to hearing from you

**Comment by enemaerke** [comment]
@GSPP anything new on this? If you've lost interest I'll just go ahead and close the issue without any code changes

**Comment by GSPP** [comment]
Alright, I suggest you close the issue for now. This is not a priority for us right now so I can't spend the time. I should have reported that back to you earlier instead of leaving the issue hanging.
