### ISSUE TITLE
Support for layout engine?

### ISSUE THREAD

**Issue by barbarosalp** [ua-parser/uap-csharp#19]
Hi,

Will there be support for layout engine?

Thanks.

**Comment by enemaerke** [comment]
Not really sure what layout engine means in this context. Could you elaborate a bit on what it is and why you need it? Thanks

**Comment by barbarosalp** [comment]
I will run some custom logic based on browser engine like Gecko, Trident, Webkit, etc...

**Comment by enemaerke** [comment]
There is no plans for allowing you to run custom logic within the library. The library is really just a wrapper around a set of regex that are iterated over for first match. So my advice is to wrap your use of the ua-parser with something that allows you to either pre-process the input or post-process the results (Unknown is used for unmatched items)

**Comment by barbarosalp** [comment]
I think I couldn't tell you enough, sorry for that.

I meant that if "ua-parser" could also parse layout engine from "user agent" string, I would use this info to run a custom logic on my own.

**Comment by enemaerke** [comment]
Ahh, okay, thanks for clarifying. 

That is currently beyond the scope of the ua-parser. Check the repo https://github.com/ua-parser/uap-core which defines the regex'es and specifically the specification: https://github.com/ua-parser/uap-core/blob/master/docs/specification.md which outlines the three parts that are extracted from the user agent string. This repo is the C# implementation of that specification and is not intended to grow beyond that, so my advise on wrapping this core logic still stands.

**Comment by barbarosalp** [comment]
I see, thank you so much for your time and also thanks for this great repo.
