### ISSUE TITLE
Latest changes have introuduced new dependancies that have broken project build

### ISSUE THREAD

**Issue by NeilP-global** [ua-parser/uap-csharp#29]
On building the latest version, the following error now occurs:

> error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="
http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the
old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

This occurs when running from Build.bat.
I believe this is due to changes to the .csproj file. I'm running visual studio 2015.

**Comment by NeilP-global** [comment]
I also get the same errors on my desktop with visual studio 2017 installed. Having said that the project builds from visual studio, but not MSBuild from build.bat

**Comment by enemaerke** [comment]
Hi @NeilP-global 

Yeah, the build.bat was not updated as part of my last update. Is there a strong push towards keeping it updated? My feeling was that you'd probably just pull out Visual Studio 17 and build it, but the rise of competing IDEs for C# might point in the other direction. 

I'll have a look at updating it shortly.

**Comment by NeilP-global** [comment]
No need to keep it updated as long as I know how it can be built, I assume that MSbuild 2017 is now required?

Need to know in order to configure a build server that ingests the project :)

**Comment by flansch** [comment]
If it's easy to repair I would prefer having a working build.bat for use in my script for updating, compiling and deploying of the parser DLL.

**Comment by enemaerke** [comment]
Have now changed the build, should now run but require VS2017. Have not experimented with a smaller requirements at this point
