### ISSUE TITLE
Why this parse device Mac and PC as 'Other'?

### ISSUE THREAD

**Issue by GovindMalviya** [ua-parser/uap-csharp#3]
I have this user agent string 

<code>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
</code>

this should be parsed device as 'Mac' and 

<code>
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36 OPR/24.0.1558.61
</code>

this should be parsed device as 'PC' but it parsing as 'Other'. Is it OK or bug? because I require device PC and Mac also.

**Comment by GovindMalviya** [comment]
I edited regexes.yaml and parsed 'PC' and 'Mac'

**Comment by Ironholds** [comment]
Why should it parse the device as "Mac"? It's identifying the specific device, not the operating system.
