### ISSUE TITLE
Make regular expressions use (CultureInvariant | Singleline)

### ISSUE THREAD

**Issue by GSPP** [ua-parser/uap-csharp#31]
* CultureInvariant: Using the current culture could introduce bugs and can have a steep performance cost.
* Singleline: This is a performance improvement. Without that option, `.` really means `[^\r\n]` or something similar to that. Executing that surely is more expensive.

Are you interested in a pull request?

Related: https://github.com/ua-parser/uap-csharp/issues/16

**Comment by enemaerke** [comment]
Sure, I'd love a PR 😄 Sounds like a reasonable thing to add to the options as defaults, which could then be overwritten by the enduser if needed for some reason

**Comment by GSPP** [comment]
Do you see a need to configure this? This should have zero negative behavior impact.

* CultureInvariant: If this causes a behavior change that's an automatic bug fix.
* Singleline: This should not change anything because user agent strings do not contain new line chars.

**Comment by GSPP** [comment]
https://github.com/ua-parser/uap-csharp/pull/32 There you go.

**Comment by enemaerke** [comment]
Thanks for the PR, I'v take the change and pushed it as part of 3.1
