### ISSUE TITLE
Support for .NET core 2.0

### ISSUE THREAD

**Issue by Ivan-Razhnou** [ua-parser/uap-csharp#35]
Hello,

could you please add support for .NET core 2.0?

**Comment by Styxxy** [comment]
The library supports both netstandard1.0 and netstandard1.3. Both are supported by .NET Core 2.x. See also the Microsoft documentation: https://docs.microsoft.com/en-us/dotnet/standard/net-standard .

**Comment by enemaerke** [comment]
I'll close this as .net core 2.0 should be able to consume netstandard libs
