### ISSUE TITLE
regexes.yaml missing

### ISSUE THREAD

**Issue by GovindMalviya** [ua-parser/uap-csharp#4]
I checkout code on my local PC and opened in visual studio, file regexes.yaml is missing.

**Comment by GovindMalviya** [comment]
All .yaml files missing in test project (UAParser.Tests) also

**Comment by GovindMalviya** [comment]
I did decompile UAParser.dll (get from nuget package) and copied regexes.yaml.

**Comment by Ironholds** [comment]
Yes, the regexes file must be downloaded separately because it's maintained in a separate repository: otherwise we'd need to push changes to every single repo on every update.
