### ISSUE TITLE
This library is obsolete, move to a new project

### ISSUE THREAD

**Issue by OrbintSoft** [ua-parser/uap-csharp#43]
Last commit is over a year ago, no one watch issue, no on watch pull request.
I tried to contact the authors in many ways, but they don't answer,

You can still use this library forking this project and loading updated yaml files, but there are a lot of architecture issue that no one will ever be interested to handle.
A yaml database of user agent is not enough in any case to handle correctly the great amount and diversity of devices that access to web today.

If you want a good User Agent parser the only solution is to move forward, but what library use?

I searched a lot a library able to replace us-parser, I found some good Javascript libraries but they can't replace the job of a server side parser.

The only solution that I found to use now a good user agent parser is to depend on a cloud service, but they are not good, for several reasons:

1) They are inefficient, because for every user agent string you need to do an http request to obtain the result
2) They are expensive, because you need to subscribe and pay a quote for the use
3) Usually they aren't real parser, but they works thanks to bug databases of useragents, but they can fail in case of weird, corrupted or hacked user agent string

So after a lot of search I found this awesome Server Side library: https://github.com/nielsbasjes/yauaa
The problems is that library is written in Java, so I decided to create a .NET porting: https://github.com/OrbintSoft/yauaa.netstandard

A lot of work is still needed to make this porting working, but the project is active, and if you contribute soon we can have our awesome .NET user agent parser and I plan to release our .nuget package.

Thank you

**Comment by NeilP-global** [comment]
Actually, ua-core is still actively updated, it's just the parser that's been abandoned. 

Last time I checked, updates to ua-core had broke the build, it's sad that this hasn't been rectified.

**Comment by OrbintSoft** [comment]
Thank you very much @enemaerke , your work is really appreciated, I still think that your library is the best user agent parser application available in C#.
Unlucky new user agents comes out every day and depend on regular expressions requires a continuative update or the library becomes almost useless.
So I continue to work to provide an alternative and I hope better user agent parser library for c#.
If you plan to maintain and update regularly this library you can close this issue.
