### ISSUE TITLE
Pixel 3 XL user agent string not returning correct device information

### ISSUE THREAD

**Issue by mjohnson-madcap** [ua-parser/uap-csharp#51]
For the following user agent string sent using Chrome on a Pixel 3 XL the device family is returning "Generic Smartphone"

Mozilla/5.0 (Linux; Android 9; Pixel 3 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.89 Mobile Safari/537.36

**Comment by enemaerke** [comment]
Sorry for the late reply. This library is a wrapper aroung the ua-parser/uap-core regular expressions that outlines all the matching, so if a particular input yields an invalid result you should create an issue in that repository
