### ISSUE TITLE
Bounding time spent in regex Match() calls

### ISSUE THREAD

**Issue by fjardon** [ua-parser/uap-csharp#55]
Hi,
First, thank you for the work you put in providing this library.

Looking into the code I see that when creating the regexes there is no `matchTimeout` parameter passed to the [constructor](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.-ctor#System_Text_RegularExpressions_Regex__ctor_System_String_System_Text_RegularExpressions_RegexOptions_System_TimeSpan_). This means that in case of catastrophic backtracking there is no guarantee for the client of the library that the call will terminate (in a reasonable time). The [recommended way](https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#controlling-backtracking) to prevent this is to use the `matchTimeout` parameter of the Regex constructor.

- Do you have a plan to prevent catastrophic backtracking at the regex level (by gatekeeping the inclusion of _bad_ regexes for instance) ?
- If not, do you plan to have a configurable `matchTimeout` ?
- Would you accept a contribution and what is the process to follow ?

Thanks,
Frederic Jardon

**Comment by enemaerke** [comment]
I did not have a plan for preventing backtracking, but it seems like a good candidate to include in the `ParserOptions` class for the library, that way it is configurable from the outside. 

Generally I rely on the regex'es delivered by the uap-core "parent" project to be well tested, but there could obviously be .NET specific issues.

I'd be happy to accept pull requests (though my track record for going through them is a bit spotty, but I'll try my best)

**Comment by fjardon** [comment]
Thanks for the reply, I will discuss this with my employer and get back to you.

**Comment by enemaerke** [comment]
Hi @fjardon 
I have uploaded a new NuGet library that exposes the MatchTimeOut via the ParserOptions (on target frameworks that allows it), so you can go ahead and try it out here: https://www.nuget.org/packages/UAParser/3.1.42

**Comment by fjardon** [comment]
Hi,
That's a very good news :)
Thank you very much.
