### ISSUE TITLE
Safari version information supplement

### ISSUE THREAD

**Issue by MagicalLeaf** [ua-parser/uap-csharp#62]
I noticed that part of the UserAgent generated by safari on the iPhone does not contain the version information of safari, so the version information of safari cannot be obtained during the parsing process. However, these UserAgents generally contain the version information of iPhone OS. I learned that because safari is a part of iOS, the version of safari is always the same as the version of iOS. Can we fill in the version information of safari by obtaining the version information of iOS when the version information of safari cannot be obtained directly?
E.g:Mozilla/5.0 (iPad; CPU OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 musical_ly_18.6.6 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/en Region/CH RevealType/Dialog isDarkMode/1 Safari/604.1 WKWebView/1
This UA character does not contain the version information of safari, but it does contain the version information of iOS. We can try to use the version information of iOS to fill in the version information of safari. From this we can know that this UA character comes from safari 14.4

**Comment by enemaerke** [comment]
This request seems to go beyond the capabilities of this parser as defined in the root project ua-parser/uap-core that concentrate on returning browser, OS and device (see https://github.com/ua-parser/uap-core/blob/master/docs/specification.md). Returning additional data is beyond the scope.

**Comment by MagicalLeaf** [comment]
Okay, thanks for answering
