### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by WeihanLi** [ua-parser/uap-csharp#64]
I found something in the source code, not sure if it's a bug, it seemed the last one should be `$9` other than `$91`?

https://github.com/ua-parser/uap-csharp/blob/809de48566c85ad5173f03d68d7819b684aa7e9e/UAParser/UAParser.cs#L516-L519

**Comment by enemaerke** [comment]
Yes, that surely looks like a typo. Good catch. The reference testing suite did not seem to trigger it so it might never have come into play, but I will fix regardless.
