### ISSUE TITLE
NuGet release for .NET Standard 2.0

### ISSUE THREAD

**Issue by holm-dk** [ua-parser/uap-csharp#69]
We would be very grateful if we could have a NuGet release targeting .NET Standard 2.0? Any chance?

**Comment by prince272** [comment]
Exactly...

**Comment by julealgon** [comment]
@holm-dk why did you close this?

@enemaerke can we get a new NuGet release of the library please? The last published version is `3.1.47` from 2021 and that doesn't have the `netstandard2.0` target yet.
